### ISSUE TITLE
웹 플럭스 vs. MVC (Boot p78)

### ISSUE THREAD

**Issue by wjddlsy** [wjddlsy/BootReact#10]
리액티브 웹 플럭스를 사용하는 가장 큰 이점은 동일한 패러다임과 함께 @MVC와 동일한 어노테이션을 사용함과 동시에 입출력에서 리액터 타입(모노 및 플럭스)를 지원한다는 것이다. 

무슨 의미일까

**Comment by MinhoLee93** [comment]
기존 MVC 타입 : 모노리틱 아키텍쳐 (Model-View-Control)
Spring Boot : 리액티브 웹 (MSA) 
위의 두가지다를 지원하므로.. 서비스에 맞게 필요한 어노테이션을 조합해서 사용하시오! 
가 아닐까..?

**Comment by wjddlsy** [comment]
오.. 똑똑해
